version: '3'
services:
  # client app far jar image (client code and dependencies)
#  hazelcast-client:
#    image: hazelcast_client_app
#    depends_on:
#      - hazelcast
#    volumes:
#      - ../resources:/configFolder
#    environment:
#      - JAVA_OPTS=-Dhazelcast.client.config=/configFolder/hazelcast-client.xml -Dhazelcast.member.address=hazelcast -Dgroup.name=hz-compose -Dgroup.password=s3crEt

  # hazelcast imdg
  hazelcast-1:
    image: hazelcast/hazelcast
    volumes:
      - ./mc.keystore:/mc.keystore
    environment:
      - TLS_ENABLED=true
      - MANCENTER_URL=https://mc:8443/hazelcast-mancenter
      - JAVA_OPTS=-Dgroup.name=hz-compose -Dgroup.password=s3crEt -Djavax.net.ssl.keyStore=/mc.keystore -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStore=/mc.keystore -Djavax.net.ssl.trustStorePassword=changeit
  hazelcast-2:
    image: hazelcast/hazelcast
    volumes:
      - ./mc.keystore:/mc.keystore
    environment:
      - TLS_ENABLED=true
      - MANCENTER_URL=https://mc:8443/hazelcast-mancenter
      - JAVA_OPTS=-Dgroup.name=hz-compose -Dgroup.password=s3crEt -Djavax.net.ssl.keyStore=/mc.keystore -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStore=/mc.keystore -Djavax.net.ssl.trustStorePassword=changeit

  #management center
  mc:
    image: hazelcast/management-center

    # persisting mancenter users db folder to local disk
    volumes:
      - ~/hazelcast-mc:/hazelcast-mc
      - ./mc.keystore:/mc.keystore
    environment:
      - MANCENTER_DATA=/hazelcast-mc
      # enable REST interface on management center
      # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
      - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true -Dhazelcast.mc.tls.enabled=true -Dhazelcast.mc.tls.keyStore=/mc.keystore -Dhazelcast.mc.tls.keyStorePassword=changeit -Dhazelcast.mc.tls.trustStore=/mc.keystore -Dhazelcast.mc.tls.trustStorePassword=changeit
    ports:
      - 8080:8080
      - 8443:8443
